###
POST http://127.0.0.1:8000/account/Signup/
Content-Type: application/json

{
    "username":"newuser",
    "email":"new@gmail.com",
    "password":"1234P"
}




###
POST  http://127.0.0.1:8000/account/Login/
Content-Type: application/json

{"username":"dan",
  "password":"1234P"}


###
POST http://127.0.0.1:8000/tasks/ 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY1MTM4MjAwLCJpYXQiOjE3NjUxMzc5MDAsImp0aSI6IjY4NmU3MWEyNTQyZDQ1ZWI5OGRiZTQ2YzQ1YWI2MmEyIiwidXNlcl9pZCI6IjBlNjRhOGNjLTNkMWEtNDMwYy05Nzg4LWI2NmQ4OGFjOGUxMyJ9.kO7EPIjLo8siLEWnNDfcBPQBsVemrBOYpEDw2pjQBCo
{
    "title":"rask",
    "reminder_time":"2025-12-09T12:43:00Z",
    "number_repeat":"YR"
}


###
GET http://127.0.0.1:8000/tasks/user-tasks/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY1MTM4MjAwLCJpYXQiOjE3NjUxMzc5MDAsImp0aSI6IjY4NmU3MWEyNTQyZDQ1ZWI5OGRiZTQ2YzQ1YWI2MmEyIiwidXNlcl9pZCI6IjBlNjRhOGNjLTNkMWEtNDMwYy05Nzg4LWI2NmQ4OGFjOGUxMyJ9.kO7EPIjLo8siLEWnNDfcBPQBsVemrBOYpEDw2pjQBCo