# Generated by Django 6.0 on 2025-12-07 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='interval_min',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tasks',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
