# Generated by Django 6.0 on 2025-12-07 19:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='detail',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='number_repeat',
            field=models.CharField(choices=[('1', 'Once'), ('D', 'Daily'), ('WK', 'Weekly'), ('M', 'Monthly'), ('Q', 'Quarterly'), ('BI', 'BiannuaLly'), ('YR', 'Yearly')], default='1', max_length=200),
        ),
    ]
